version: '3.7'
services:
    bodypix:
        image: bodypix
        init: true
        environment:
            ARCHITECTURE: ResNet50
            IRES: 1
            MULTI: 1
            QBYTES: 4
        build:
            context: ./bodypix
        read_only: true

    fakecam:
        image: fakecam
        init: true
        build:
            context: ./fakecam
        read_only: true
        volumes:
          - /surviving-data/Pictures/backgrounds/5d28a7d1be8d2.jpg:/src/background.jpg:ro
#          - /surviving-data/Pictures/backgrounds/this_is_fine.jpg:/src/background.jpg:ro
#          - /surviving-data/Pictures/backgrounds/popup_2_21_5.jpg:/src/background.jpg:ro
        #   - /surviving-data/Pictures/backgrounds/marias-kontorsvagg.jpg:/src/background.jpg:ro
        #   - /path/to/foreground.jpg:/src/foreground.jpg:ro
        #   - /path/to/foreground-mask.png:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - /dev/video0:/dev/video0
            # output (virtual webcam)
            - /dev/video2:/dev/video2
            # accelerated processing (gpu)
#            - /dev/nvidia0:/dev/nvidia0
        depends_on:
            - bodypix
        entrypoint: [ 'python3', '-u', 'fake.py', '-B', 'http://bodypix:9000/', "--no-foreground", "--no-background", "--background-blur=50"]
