version: '3.7'
services:
    bodypix:
        image: bodypix
        init: true
        build:
            context: ./bodypix
        read_only: true

    fakecam:
        image: fakecam
        init: true
        build:
            context: ./fakecam
        read_only: true
        volumes:
          - /home/pczarkowski/Pictures/bg.jpg:/src/background.jpg:ro
        #   - /path/to/foreground.jpg:/src/foreground.jpg:ro
        #   - /path/to/foreground-mask.png:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - /dev/video3:/dev/video0
            # output (virtual webcam)
            - /dev/video0:/dev/video2
        depends_on:
            - bodypix
        entrypoint: [ 'python3', '-u', 'fake.py', '-B', 'http://bodypix:9000/', "--no-foreground"]
